name = "bytetalk"
license = "MIT"
licenselink = "https://github.com/jrutheiser/hugo-lithium-theme/blob/master/LICENSE.md"
description = "Lithium minimal theme"
homepage = "https://github.com/jrutheiser/hugo-lithium-theme"
tags = ["podcast"]
features = ["podcast"]
min_version = 0.15

